[user]
name = "Grigory Petrov"
email = "grigoryvp@gmail.com"

[core]
editor = "code"
autocrlf = "input"
safecrlf = false
# Hunk header descriptions https://github.com/git/git/blob/master/userdiff.c
attributesfile = "~/.gitattributes"

[format]
pretty = "oneline"

[push]
default = "simple"

[fetch]
# Fixes "cannot lock ref" macOS case sensetive issue.
prune = true

[alias]
ch = "checkout"
a = "add"
aa = "add ."
ap = "add -p"
cm = "commit -m"
ps = "push"
pl = "pull --all --prune --rebase"
st = "status --short --branch"
lg = "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
br = "branch"
di = "diff --ignore-space-change"
diw = "diff --ignore-space-change --color-words"
dic = "diff --ignore-space-change --cached"
dicw = "diff --ignore-space-change --color-words --cached"
dit = "difftool --ignore-space-change"
